Blog/urls.py
from django.urls import path, include
from rest_framework import routers

from Blog import views
from Blog.api_views import BlogView, CommentView

app_name = 'Blog'

router = routers.DefaultRouter()
router.register('blog', BlogView)
router.register('comment', CommentView)

urlpatterns = [
    path('', views.home, name='home'),
    path('details/<str:title>', views.blog_page, name='blog_page'),
    path('api/', include(router.urls))
]

DU_E_Library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin-manager/', admin.site.urls),
    path('', include('Library.urls')),
    path('blog/', include('Blog.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = "Library.views.error_400"
handler403 = "Library.views.error_403"
handler404 = "Library.views.error_404"
handler500 = "Library.views.error_500"

Library/urls.py
from django.urls import path, include
from rest_framework import routers

from Library import views
from Library.api_views import ClienteleView, PasswordView, EbookView, JournalView, LibraryFileView

app_name = 'Library'

router = routers.DefaultRouter()
router.register('clientele', ClienteleView)
router.register('password', PasswordView)
router.register('ebook', EbookView)
router.register('journal', JournalView)
router.register('library-file', LibraryFileView)

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('login', views.log_in, name='login'),
    path('login/forgot-password', views.forgotten_password, name='forgot_password'),
    path('login/forgot-password/<int:clientele_id>/retrieve-password', views.password_retrieval, name='password_retrieval'),
    path('account/<int:clientele_id>/retrieve-password/update-password', views.update_password, name='update_password'),
    path('admin/', views.library_admin, name='library_admin'),
    path('admin/approve-clientele/<int:clientele_id>', views.approve_clientele, name='approve_clientele'),
    path('admin/reject-clientele/<int:clientele_id>', views.reject_clientele, name='reject_clientele'),
    path('admin/approve-journal/<int:journal_id>', views.approve_journal, name='approve_journal'),
    path('admin/reject-journal/<int:journal_id>', views.reject_journal, name='reject_journal'),
    path('register', views.register, name='register'),
    path('account/update-profile-image', views.update_profile_image, name='update_profile_image'),
    path('account/repository', views.repository, name='repository'),
    path('account/logout', views.log_out, name='logout'),
    path('api/', include(router.urls))
]

Library/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from Library.extra import ContentTypeRestrictedFileField


class Clientele(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=False)
    first_name = models.CharField(max_length=50, null=False)
    clientele_id = models.CharField(max_length=30, null=False)
    sex = models.CharField(max_length=10, null=False, choices=[('Male', 'Male'), ('Female', 'Female')])
    phone_no = models.CharField(max_length=20, null=False)
    email = models.EmailField(null=False)
    role = models.CharField(max_length=10, null=False, choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Admin', 'Admin')])
    image = ContentTypeRestrictedFileField(upload_to='LibRead/profile-image',
                                           max_upload_size=5242880,
                                           content_types=['image/jpeg', 'image/jpg', 'image/png'],
                                           null=True,
                                           blank=True,
                                           max_length=250)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user} -> {self.last_name} {self.first_name}"


class Password(models.Model):
    clientele = models.ForeignKey(Clientele, on_delete=models.CASCADE)
    recovery_password = models.CharField(max_length=12, null=False)
    time = models.DateTimeField(null=False)
    is_active = models.BooleanField(null=False, default=True)

    def __str__(self):
        return f"{self.clientele} -> {self.recovery_password}"

    def expiry(self):
        if (timezone.now() - self.time) >= timezone.timedelta(hours=1):
            self.delete()
        else:
            pass


class Ebook(models.Model):
    title = models.CharField(max_length=250, null=False)
    authors = models.CharField(max_length=200, null=False)
    description = models.CharField(max_length=250, null=False)
    date = models.DateTimeField(null=False)
    file = ContentTypeRestrictedFileField(upload_to="LibRead/ebooks/",
                                          max_upload_size=5242880,
                                          content_types=['application/pdf', 'application/zip'],
                                          null=False,
                                          max_length=250)

    def __str__(self):
        return f"{self.title} -> {self.authors}"

    def post_update(self):
        if (timezone.now() - self.date) < timezone.timedelta(days=1):
            return "recently posted"
        elif (timezone.now() - self.date) > timezone.timedelta(weeks=4):
            return "outdated post"
        else:
            return ""

    def duration_of_post(self):
        return timezone.now() - self.date


class Journal(models.Model):
    title = models.CharField(max_length=250, null=False)
    authors = models.CharField(max_length=200, null=False)
    description = models.CharField(max_length=250, null=True)
    date = models.DateTimeField(null=False)
    file = ContentTypeRestrictedFileField(upload_to="LibRead/journals/",
                                          max_upload_size=5242880,
                                          content_types=['application/pdf', 'application/zip'],
                                          null=False,
                                          max_length=250)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} -> {self.authors}"

    def post_update(self):
        if (timezone.now() - self.date) < timezone.timedelta(days=1):
            return "recently posted"
        elif (timezone.now() - self.date) > timezone.timedelta(weeks=4):
            return "outdated post"
        else:
            return ""

    def duration_of_post(self):
        return timezone.now() - self.date


class LibraryFile(models.Model):
    programme = models.CharField(max_length=250, null=False, choices=[
        ('Computer Science', 'Computer Science'),
        ('Software Engineering', 'Software Engineering'),
        ('Cyber Security', 'Cyber Security'),
        ('Biochemistry', 'Biochemistry'),
        ('Industrial Chemistry', 'Industrial Chemistry'),
        ('Business Administration', 'Business Administration'),
        ('Mass Communication', 'Mass Communication'),
        ('Criminology', 'Criminology'),
        ('Microbiology', 'Microbiology'),
        ('Economics', 'Economics'),
        ('Accounting', 'Accounting'),
    ])
    ebook = models.ManyToManyField(Ebook, blank=True, null=True)
    journal = models.ManyToManyField(Journal, blank=True, null=True)

    def __str__(self):
        return self.programme

Library/views.py
import random
import string

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags

from Blog.models import Blog
from DU_E_Library.settings import EMAIL_HOST_USER
from Library.forms import RegistrationForm, LoginForm, ForgotPasswordForm, PasswordRetrievalForm, UpdatePasswordForm, \
    UpdateImageForm, EbookForm, JournalForm, BlogForm
from Library.models import Clientele, Password, Journal, Ebook, LibraryFile

random = random.Random()


def home(request):
    all_blogs = Blog.objects.all()
    context = {'all_blogs': all_blogs}
    if request.user.is_authenticated and not request.user.is_superuser:
        current_clientele = get_object_or_404(Clientele, clientele_id=request.user.username)
        context = {'current_clientele': current_clientele, 'all_blogs': all_blogs}
        return render(request, 'library/library_home.html', context)
    else:
        return render(request, 'library/library_home.html', context)


def about(request):
    context = {}
    if request.user.is_authenticated and not request.user.is_superuser:
        current_clientele = get_object_or_404(Clientele, clientele_id=request.user.username)
        context = {'current_clientele': current_clientele}
    return render(request, 'library/about.html', context)


def contact(request):
    context = {}
    if request.user.is_authenticated and not request.user.is_superuser:
        current_clientele = get_object_or_404(Clientele, clientele_id=request.user.username)
        context = {'current_clientele': current_clientele}
    return render(request, 'library/contact.html', context)


def log_in(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        return HttpResponseRedirect(reverse('Library:repository'))
    else:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                clientele_id = form.cleaned_data['user_id'].strip()
                password = form.cleaned_data['password'].strip()
                user = authenticate(request, username=clientele_id, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(request, "Login successful")
                    return HttpResponseRedirect(reverse('Library:repository'))
                else:
                    messages.error(request, "Invalid login details")
                    return HttpResponseRedirect(reverse('Library:login'))
        else:
            form = LoginForm()
        return render(request, 'library/login.html', {'form': form})


def forgotten_password(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        return HttpResponseRedirect(reverse('Library:repository'))
    else:
        if request.method == 'POST':
            form = ForgotPasswordForm(request.POST)
            if form.is_valid():
                clientele_id = form.cleaned_data['user_id'].strip()
                email = form.cleaned_data['email'].strip()
                all_user = User.objects.all()
                for user in all_user:
                    if user.username == clientele_id and user.email == email:
                        clientele = Clientele.objects.get(user=user)
                        recovery_password = ''.join(
                            [random.choice(string.ascii_letters + string.digits) for i in range(12)])
                        subject = 'Password Recovery'

                        all_passwords = Password.objects.filter(is_active=True)
                        for password in all_passwords:
                            if password.clientele == clientele and password.is_active:
                                password.is_active = False
                                break

                        Password.objects.create(clientele=clientele, recovery_password=recovery_password,
                                                time=timezone.now())

                        msg = f"Recovery password will expire after an hour. Your password is displayed below"
                        context = {'subject': subject, 'msg': msg, 'recovery_password': recovery_password, 'id': clientele.id}
                        html_message = render_to_string('library/msg.html', context=context)

                        send_mail(subject, msg, EMAIL_HOST_USER, [email], html_message=html_message, fail_silently=False)

                        messages.success(request, "Recovery password has been successfully sent")
                        return HttpResponseRedirect(reverse('Library:password_retrieval', args=(clientele.id,)))
                else:
                    messages.error(request, "User profile not found")
                    return HttpResponseRedirect(reverse('Library:forgot_password'))
        else:
            form = ForgotPasswordForm()
        return render(request, 'library/forgot_password.html', {'form': form})


def password_retrieval(request, clientele_id):
    all_passwords = Password.objects.filter(is_active=True)
    for password in all_passwords:
        password.expiry()

    if request.user.is_authenticated and not request.user.is_superuser:
        return HttpResponseRedirect(reverse('Library:repository'))
    else:
        if request.method == 'POST':
            form = PasswordRetrievalForm(request.POST)
            if form.is_valid():
                password = form.cleaned_data['password'].strip()
                all_password = Password.objects.all()
                clientele = get_object_or_404(Clientele, id=clientele_id)

                for passcode in all_password:
                    if passcode.clientele == clientele and passcode.recovery_password == password and passcode.is_active:
                        subject = 'Password Recovery Successful'
                        msg = "Account has been successfully recovered. Kindly proceed to update your password"
                        context = {'subject': subject, 'msg': msg}
                        html_message = render_to_string('library/msg.html', context=context)

                        send_mail(subject, msg, EMAIL_HOST_USER, [clientele.email], html_message=html_message,
                                  fail_silently=False)

                        messages.success(request, 'Account has been successfully recovered. Kindly update your password')
                        return HttpResponseRedirect(reverse('Library:update_password', args=(clientele_id,)))
                else:
                    messages.error(request,
                                   "Incorrect recovery password. Click on resend to get the retrieval password again")
                    return HttpResponseRedirect(reverse('Library:password_retrieval', args=(clientele_id,)))
        else:
            form = PasswordRetrievalForm()
        current_clientele = get_object_or_404(Clientele, id=clientele_id)
        context = {'current_clientele': current_clientele, 'clientele_id': clientele_id, 'form': form}
        return render(request, 'library/password_retrieval.html', context)


def update_password(request, clientele_id):
    if request.method == 'POST':
        form = UpdatePasswordForm(request.POST)
        if form.is_valid():
            password1 = form.cleaned_data['password'].strip()
            password2 = form.cleaned_data['confirm_password'].strip()

            if password1 == password2:
                user = Clientele.objects.get(id=clientele_id).user
                user.set_password(password1)
                user.save()

                subject = 'Password Update Successful'
                msg = "Account password has  been successfully changed"
                context = {'subject': subject, 'msg': msg}
                html_message = render_to_string('library/msg.html', context=context)

                send_mail(subject, msg, EMAIL_HOST_USER, [user.email], html_message=html_message,
                          fail_silently=False)

                messages.success(request, 'Password successfully changed')
                return HttpResponseRedirect(reverse('Library:login'))
            else:
                messages.error(request, "Password does not match")
                return HttpResponseRedirect(reverse('Library:update_password', args=(clientele_id,)))
    else:
        form = UpdatePasswordForm()
    current_clientele = get_object_or_404(Clientele, id=clientele_id)
    context = {'current_clientele': current_clientele, 'clientele_id': clientele_id, 'form': form}
    return render(request, 'library/update_password.html', context)


def register(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        return HttpResponseRedirect(reverse('Library:repository'))
    else:
        if request.method == 'POST':
            form = RegistrationForm(request.POST)
            if form.is_valid():
                last_name = form.cleaned_data['last_name'].capitalize().strip()
                first_name = form.cleaned_data['first_name'].capitalize().strip()
                clientele_id = form.cleaned_data['user_id'].strip()
                sex = form.cleaned_data['sex'].capitalize().strip()
                phone_no = form.cleaned_data['phone_number'].strip()
                email = form.cleaned_data['email'].strip()
                role = form.cleaned_data['role'].capitalize().strip()

                all_clienteles = Clientele.objects.all()

                for clientele in all_clienteles:
                    if clientele_id == clientele.clientele_id:

Library/templates/library/about.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
<title>About Us</title>
{% endblock %}

{% block user %}
{% if current_clientele %}
<div>
    <small style="color:white">{{ current_clientele.clientele_id }}</small>
</div>
{% endif %}
{% endblock %}

{% block content %}
<!-- Start breadcrumb area -->
<div class="ht__breadcrumb__area bg-image--9 lazy">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__inner text-center">
                    <h2 class="breadcrumb-title">About us</h2>
                    <nav class="breadcrumb-content">
                        <a class="breadcrumb_item" href="{% url 'Library:home' %}">Home</a>
                        <span class="brd-separator">/</span>
                        <span class="breadcrumb_item active">About us</span>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcrumb area -->
<!-- Start About Area -->
<div class="page-about about_area bg--white section-padding--lg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section__title--3 text-center pb--30">
                    <h2>Our Process Skill Of High</h2>
                    <p>the right people for your project</p>
                </div>
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-lg-6 col-sm-12 col-12">
                <div class="content text-start text_style--2">
                    <h2>we have skills to show</h2>
                    <div class="skill-container">
                        <!-- Start single skill -->
                        <div class="single-skill">
                            <p>Customer Favorites</p>
                            <div class="progress">
                                <div class="progress-bar wow fadeInLeft" data-wow-duration="0.8s"
                                     data-wow-delay=".5s" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                     aria-valuemax="100" style="width:90%"><span class="pen-lable"></span>
                                </div>
                            </div>
                        </div>
                        <!-- End single skill -->
                        <!-- Start single skill -->
                        <div class="single-skill">
                            <p>Popular Authors</p>
                            <div class="progress">
                                <div class="progress-bar wow fadeInLeft" data-wow-duration="0.8s"
                                     data-wow-delay=".5s" role="progressbar" aria-valuenow="95" aria-valuemin="0"
                                     aria-valuemax="100" style="width:95%"><span class="pen-lable"></span>
                                </div>
                            </div>
                        </div>
                        <!-- End single skill -->
                        <!-- Start single skill -->
                        <div class="single-skill">
                            <p>Bestselling Series</p>
                            <div class="progress">
                                <div class="progress-bar wow fadeInLeft" data-wow-duration="0.8s"
                                     data-wow-delay=".5s" role="progressbar" aria-valuenow="93" aria-valuemin="0"
                                     aria-valuemax="100" style="width:93%"><span class="pen-lable"></span>
                                </div>
                            </div>
                        </div>
                        <!-- End single skill -->
                        <!-- Start single skill -->
                        <div class="single-skill">
                            <p>Bargain Books</p>
                            <div class="progress">
                                <div class="progress-bar wow fadeInLeft" data-wow-duration="0.8s"
                                     data-wow-delay=".5s" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                     aria-valuemax="100" style="width:90%"><span class="pen-lable"></span>
                                </div>
                            </div>
                        </div>
                        <!-- End single skill -->
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-sm-12 col-12">
                <div class="content">
                    <h3>Buy Book</h3>
                    <h2>Different Knowledge</h2>
                    <p class="mt--20 mb--20">Claritas est etiam processus dynamicus, qui sequitur mutationem
                        consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum
                        claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta
                        decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in
                        futurum.</p>
                    <strong>London Address</strong>
                    <p>34 Parer Place via Musk Avenue Kelvin Grove, QLD, 4059</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End About Area -->
<!-- Start Team Area -->
<section class="wn__recent__post pt--20">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section__title text-center">
                        <h2 class="title__be--2">The School <span class="color--theme" style="color: #1C1C4A">Librarian</span></h2>
                    </div>
                    <div class="section__title text-center is-128x128 image">
                          <img class="is-rounded lazy" data-src="https://bulma.io/images/placeholders/128x128.png">
                    </div>
                </div>
            </div>
            <div class="row mt--50">
                <p class="mt--20 mb--20">Claritas est etiam processus dynamicus, qui sequitur mutationem
                            consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum
                            claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta
                            decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in
                            futurum.</p>
            </div>
        </div>
    </section>
<!-- End Team Area -->
{% endblock %}

Library/templates/library/register.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
<title>E-Library | Register</title>
{% endblock %}

{% block user %}
{% if current_clientele %}
<div>
    <small style="color:white">{{ current_clientele.clientele_id }}</small>
</div>
{% endif %}
{% endblock %}

{% block content %}
<!-- Start breadcrumb area -->
<div class="ht__breadcrumb__area bg-image--6">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__inner text-center">
                    <h2 class="breadcrumb-title">Register</h2>
                    <nav class="breadcrumb-content">
                        <a class="breadcrumb_item" href="{% url 'Library:home' %}">Home</a>
                        <span class="brd-separator">/</span>
                        <span class="breadcrumb_item active">Register</span>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcrumb area -->
<!-- Start Message area -->
{% for message in messages %}
{% if message.tags == "success" %}
<section class="my_account_area pt--80 pb--55 bg--white" id="suc-sec">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-6">
                <article class="message is-success">
                    <div class="message-header">
                        <p>Success</p>
                        <button class="delete" aria-label="delete"></button>
                    </div>
                    <div class="message-body">
                        <em>{{ message }}</em>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>
{% else %}
<section class="my_account_area pt--80 pb--55 bg--white" id="err-sec">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-6">
                <article class="message is-danger">
                    <div class="message-header">
                        <p>Error</p>
                        <button class="delete" aria-label="delete"></button>
                    </div>
                    <div class="message-body">
                        <em>{{ message }}</em>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>
{% endif %}
{% endfor %}
<!-- End Message area -->
<!-- Start My Registration Area -->
<section class="my_account_area pt--80 pb--55 bg--white">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-6">
                <div class="my__account__wrapper">
                    <h3 class="account__title">Register</h3>
                    <form action="" method="post"
                          style="background-color:#D3D3EE; border-radius:5%">
                        {% csrf_token %}
                        <div class="account__form" style="border:0">
                            {% include 'library/django_form.html' with form=form %}
                            <div>
                                <button class="button is-fullwidth is-rounded is-link label" type="submit">Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End My Registration Area -->
{% endblock %}

Library/templates/library/upload_image.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>E-Library | Upload Profile Picture</title>
{% endblock %}

{% block user %}
{% if current_clientele %}
<div>
    <small style="color:white">{{ current_clientele.clientele_id }}</small>
</div>
{% endif %}
{% endblock %}

{% block content %}
<!-- Start breadcrumb area -->
<div class="ht__breadcrumb__area bg-image--6">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__inner text-center">
                    <h2 class="breadcrumb-title">Change Profile Picture</h2>
                    <nav class="breadcrumb-content">
                        <a class="breadcrumb_item" href="{% url 'Library:home' %}">Home</a>
                        <span class="brd-separator">/</span>
                        <a class="breadcrumb_item active" href="{% url 'Library:login' %}">Change Profile Picture</a>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcrumb area -->
<!-- Start Message area -->
{% for message in messages %}
{% if message.success %}
<section class="my_account_area pt--80 pb--55 bg--white" id="suc-sec">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-6">
                <article class="message is-success">
                    <div class="message-header">
                        <p>Success</p>
                        <button class="delete" aria-label="delete"></button>
                    </div>
                    <div class="message-body">
                        <em>{{ message }}</em>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>
{% else %}
<section class="my_account_area pt--80 pb--55 bg--white" id="err-sec">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-6">
                <article class="message is-danger">
                    <div class="message-header">
                        <p>Error</p>
                        <button class="delete" aria-label="delete"></button>
                    </div>
                    <div class="message-body">
                        <em>{{ message }}</em>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>
{% endif %}
{% endfor %}
<!-- End Message area -->
<!-- Start Password Retrieval Area -->
<section class="my_account_area pt--80 pb--55 bg--white">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-6">
                <div class="my__account__wrapper">
                    <h3 class="account__title">Upload Profile Picture</h3>
                    <form action="{% url 'Library:update_profile_image' %}" method="post" enctype="multipart/form-data"
                          style="background-color:#D3D3EE; border-radius:5%">
                        {% csrf_token %}
                        <div class="account__form" style="border:0">
                            <div class="field">
                                <label class="label">Add image <span>*</span></label>
                                <div class="has-name is-fullwidth">
                                    <label class="file-label input">
                                        <input type="file" name="image" required>
                                    </label>
                                </div>
                            </div>
                            <div>
                                <button class="button is-fullwidth is-rounded is-link label" type="submit">Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Password Retrieval Area -->
{% endblock %}